title: Organic chemistry unit
author: Jesuisgmo
email: jesuisgmo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Organic chemistry unit tasks and tips!

# social links
github_username: Jesuisgmo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
